name:                order-graph
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/runeksvendsen/order-graph#readme
license:             BSD3
author:              Rune K. Svendsen
maintainer:          runesvend@gmail.com
copyright:           CC0
category:            value

default-extensions:
- FlexibleContexts

dependencies:
  - base >= 4.7 && < 5
  - protolude
  - transformers
  - orderbook
  - unordered-containers
  - impure-containers
  - text
  - primitive
  - safe-money
  - heap
  - hashable
  - deepseq
  - pretty-show
  - thrist
  - vector

library:
  source-dirs: src
  ghc-options:
  - -Wall

executables:
  order-graph-exe:
    main: Main.hs
    source-dirs: app
    dependencies:
    - base
    - orderbook
    - crypto-venues
    - order-graph
    - logging
    - http-client
    - http-client-tls
    - monad-parallel
    - unordered-containers
    - safe-money
    - vector
    - criterion
    - aeson
    - directory

tests:
  crypto-venues-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - order-graph
    - vector
    - HUnit
    - hspec-expectations
    - hspec-expectations-pretty-diff
    - QuickCheck
    - hspec
    - tasty
    - tasty-smallcheck
    - tasty-quickcheck
    - smallcheck
    - hspec-smallcheck
    - random-shuffle
